name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy Lambda
        run: |
          aws lambda create-function \
            --function-name my-function \
            --runtime nodejs12.x \
            --handler index.handler \
            --zip-file fileb://function.zip \
            --role arn:aws:iam::123456789012:role/my-lambda-role
      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name my-function \
            --payload '{"name": "world"}' \
            response.json
